version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "~/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/selenoid/config/video:/opt/selenoid/video"
      - "~/selenoid/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/home/alexey/selenoid/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    depends_on:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
  selenoid-video:
    image: "selenoid/video-recorder"
    network_mode: bridge
    depends_on:
      - selenoid

  jenkins:
    image: "kazimsarikaya/jenkins-python3"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8081:8080"
    container_name: "my-jenkins"
    user: root
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
